name: ptk
description: Puzzak's ToolKit

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+10

environment:
  sdk: ^3.0.0


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  xml: ^6.5.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  material_design_icons_flutter: 7.0.7296
  dynamic_color: ^1.6.9
  device_info_plus: ^10.1.1
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.71.0
  flutter_markdown: 0.7.7+1
  fluttertoast: ^8.1.1
  visibility_detector: ^0.4.0+2
  timeago: ^3.7.1
  flutter_foreground_task: ^9.2.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/authors.json
    - assets/data/demo_dictionary.json
    - assets/translations/languages.json
    - assets/translations/en.json
    - assets/translations/uk.json
    - assets/statuspage/component_dictionary.json